### PR TITLE
Make it compilable with 7.10

### PR DESCRIPTION
**Pull request by dredozubov**
Any chance to see it on hackage?

---
This change is [Reviewable](https://reviewable.io/reviews/k0001/haskell-money/1)

### CODE REVIEW

**Comment by k0001** [comment]
@dredozubov I'm sorry, I didn't notice this before and I just pushed this package to Hackage. I'll introduce your changes and have them shipped in the next version.

I didn't know anybody was using this :)

**Comment by k0001** [comment]
I published this as `safe-money` in Hackage, by the way.

**Comment by k0001** [comment]
Fixed in e9785033d14d8828fd1b71f3e524da3d5fb59914

**Comment by dredozubov** [comment]
I ended up not using it, but it's good to know it's on hackage now.
Вт, 27 дек. 2016 г. в 2:37, Renzo Carbonara <notifications@github.com>:

**Pull request closed without merging**
