### PR TITLE
Tweak safe-money.cabal

### PR DESCRIPTION
**Pull request by hvr**
This fixes a few minor issues with the `.cabal` file I noticed

 - flags toggling dependencies or features ought to be manual, otherwise the cabal solver can toggle them during the solving process (in an non always obvious way)
 - This package only compiles with GHC 8.0 currently (despite #1 having been merged), so the lower bound `base >=4.9` encodes this
 - The remaining library dependencies ought to have accurate version bounds as well for Hackage to help ensure old versions don't become uninstallable over time

If you have any questions, please let me know!

### CODE REVIEW

**Comment by k0001** [comment]
@hvr thanks for this! 

Is it bad for these flags to be `automatic`? My understanding is that `Cabal` will try to build (for example) this library with the `aeson` flag enabled if the `aeson` library is installed, and otherwise it will build with the `aeson` flag disabled. I don't think this is particularly bad. 

I'll take a look at that `base` issue, #1 should have fixed it but maybe I missed something. 

And you are right about the package dependencies needing explicit version bounds, I completely forgot about it since I'm using Nix so I don't usually pay attention to that.

**Comment by hvr** [comment]
> My understanding is that Cabal will try to build (for example) this library with the aeson flag enabled if the aeson library is installed, and otherwise it will build with the aeson flag disabled. I don't think this is particularly bad.

That may be a reasonable intuition, but it's not how automatic flags work :-)

While it's obviously true that if the `aeson` flag is enabled, then `aeson` must be part of the install-plan as well, the inverse is not true: you can easily end up with an install-plan which includes `aeson` but without the `aeson` flag being enabled; there's really no guarantee that the `aeson` flag will be enabled when `aeson` is part of the build-plan; in other words; automatic flags mean the solver is allowed to toggle them arbitrarily (while satisfying all constraints)

**Comment by k0001** [comment]
@hvr but... is that problem? I mean, does it matter whether the `aeson` flag is enabled or not? As long as the thing can successfully build with either the `aeson` library present or not, that should be more than sufficient. Of course I can change this to `manual`, but I think I prefer the behavior from `automatic`.

And by the way, I just fixed the GHC 7.10 build in a799803310f9bd2bdab8d129802e13ae524e47d4

**Comment by k0001** [comment]
Update: I just tried this, and with `automatic` it effectively builds either with or without the `aeson` library being present, which was my goal really. Whether the flag is toggled or not is not very important to me. The same applies to the other dependencies (`store`, `hashable`, `cereal`, `binary`, `deepseq`). This is satisfactory to me. Care to elaborate why I shouldn't be doing this?

**Comment by hvr** [comment]
@k0001 the problem is that your package version doesn't accurately define your API anymore. And this is an important property, because if some other package depends on your package, it becomes rather fragile if that package relies on those JSON instances to be provided, since this API feature depends on a hidden "degree of freedoms" (i.e. cabal flag settings) that can't be expressed via `build-depends`. By design, you can't express that you need `safe-money` with the `aeson` flag enabled; you can only express that you need a specific version range of `safe-money`. This is the short gist of it. I should probably write something into the cabal user guide about this, as we don't want users to use automatic flags for this, and `cabal check` will probably make this a warning or an error in the future.

**Comment by k0001** [comment]
@hvr hmmm, I understand. OK, I'll set these to `manual` then. Thanks for your input!

**Comment by k0001** [comment]
I just merged this. Thanks! I'll upload to Hackage shortly.

**Pull request closed without merging**
